version: '3'

services:
  app:
    container_name: movies-info-app-dev
    image: movies-info-app-dev
    build:
      context: .
      target: development
    env_file:
    - .env
    volumes:
      - ./src:/app/src
    stdin_open: true
    ports:
      - 3000:3000
